#!/bin/sh
exec 2>&1
echo "*** starting dbus-rvc-renogy ***"
. /etc/profile.d/profile.sh
[ ! -f /data/dbus-rvc-renogy/config ] || . /data/dbus-rvc-renogy/config
exec softlimit -d 100000000 -s 1000000 -a 100000000 \
    /data/dbus-rvc-renogy/dbus-rvc-renogy.py
